openapi: 3.0.1
info:
  title: Car Hire Rental
  version: 0.1.0
  contact:
    name: Marius Moraru
  description: Car Hire Rental API
servers:
  - url: http://localhost:{port}
    description: local environment
    variables:
      port:
        default: '8090'
tags:
  - name: rental
    description: Rental resource

security:
  - oAuth:
      - write
      - read
paths:
  # The endpoints for the rental resource
  /rental:
    post:
      tags:
        - rental
      description: Creates a rental
      operationId: createRental
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRentalRequest'
        description: Creates a rental
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
          description: CreateResponse
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
          description: Unauthorized
        '422':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnprocessableEntityResponse"
          description: UnprocessableEntity
        '500':
          $ref: '#/components/responses/Unauthorized'
      summary: Creates an user
  /rental/rental_entries:
    get:
      tags:
        - rental
      description: List all rentals to date
      operationId: listRental
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RentalResponse'
          description: List all rented cars
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
          description: Unauthorized
        '422':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnprocessableEntityResponse"
          description: UnprocessableEntity
        '500':
          $ref: '#/components/responses/Unauthorized'
  /rental/{rentalId}:
    get:
      tags:
        - rental
      description: Return a specific rental by id
      summary: "Find rented car by ID"
      operationId: getRentalById
      parameters:
        - name: rentalId
          in: path
          description: ID of rental service to return
          required: true
          schema:
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RentalResponse'
          description: List all users
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
          description: Unauthorized
        '422':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnprocessableEntityResponse"
          description: UnprocessableEntity
        '500':
          $ref: '#/components/responses/Unauthorized'
    patch:
      tags:
        - rental
      summary: Updates  a specific rental
      description: This can only be done by the logged in user.
      operationId: updateRental
      parameters:
        - name: rentalId
          in: path
          description: "user that needs to be updated"
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRentalRequest'
        description: Updates a rental
        required: true
      responses:
        '200':
          description: "Update successfull"
        '400':
          description: "Invalid rental supplied"
        '404':
          description: "Rental not found"
        '422':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnprocessableEntityResponse"
          description: UnprocessableEntity
    delete:
      tags:
        - rental
      summary: Deletes a rental
      description: This can only be done by the logged in user.
      operationId: deleteRental
      parameters:
        - name: rentalId
          in: path
          description: The id of the user that needs to be deleted
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: "Resource deleted successfull"
        '400':
          description: "Invalid rental supplied"
        '404':
          description: "Rental not found"
        '422':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnprocessableEntityResponse"
          description: UnprocessableEntity
components:
  responses:
    Unauthorized:
      description: unauthorized response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/UnauthorizedResponse'
    BadRequest:
      description: bad request
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ValidationDTO'
    ServerError:
      description: internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDTO'
  schemas:
    UnauthorizedResponse:
      description: The response when an user is not uthorized to access a specific resource.
      properties:
        message:
          description: The message to be displayed
          type: string
    CreateUserRequest:
      description: Create user details.
      properties:
        email:
          description: User's email
          type: string
        password:
          description: User's password
          type: string
        username:
          description: Username of the user
          type: string
        firstName:
          description: First name of the user
          type: string
        lastName:
          description: Last name of the user
          type: string
        country:
          description: Contry of residence for the user
          type: integer
        status:
          description: User status
          enum:
            - ACTIVE
            - DELETED
    UserResponse:
      description: List user details.
      properties:
        id:
          description: User id
          type: integer
        email:
          description: User's email
          type: string
        username:
          description: Username of the user
          type: string
        firstName:
          description: First name of the user
          type: string
        lastName:
          description: Last name of the user
          type: string
        country:
          description: Contry of residence for the user
          type: string
        license_number:
          description: License number
          type: string
        status:
          description: User status
          enum:
            - ACTIVE
            - DELETED
    SuccessResponse:
      description: Success response when an user is created
      properties:
        id:
          description: User id
          type: integer
    ValidationDTO:
      type: object
      properties:
        code:
          type: string
        field:
          type: string
        description:
          type: string
    ErrorDTO:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    UnprocessableEntityResponse:
      description: "List of JSON-API spec compliant error response objects"
      properties:
        errors:
          description: "List of errors"
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
      required:
        - errors
      type: object
    ValidationError:
      description: JSON-API spec compliant error response object
      properties:
        code:
          description: Code representing reason for error
          enum:
            - INVALID_CONSTRAINT
            - INVALID_FORMAT
            - INVALID_TYPE
            - INVALID_ENUM_VALUE
            - IN_USE
            - NOT_EDITABLE
            - REQUIRED
          type: string
        detail:
          description: Error detail
          nullable: true
          type: string
      title: ValidationError
      type: object
    CreateCarRequest:
      description: Create car details.
      properties:
        make:
          description: car's maker
          type: string
        model:
          description: model of the car
          type: string
        year:
          description: the year on which the car war build
          type: integer
        mileage:
          description: Number of kilometers that a car holds
          type: integer
        fuel:
          description: Fuel of the car
          enum:
            - GASOLINE
            - DIESEL
            - LIQUEFIED_NATURAL_GAS
            - HYBRID
            - ELECTRIC
        carClass:
          description: Car class
          enum:
            - COMPACT
            - EXECUTIVE
            - MINIVAN
            - SUV
        plateNumber:
          description: Plate number
          type: string
        status:
          description: Car status
          enum:
            - ACTIVE
            - DELETED
    CarResponse:
      properties:
        id:
          description: car id
          type: integer
        make:
          description: car's maker
          type: string
        model:
          description: model of the car
          type: string
        year:
          description: the year on which the car war build
          type: integer
        mileage:
          description: Number of kilometers that a car holds
          type: integer
        fuel:
          description: Fuel of the car
          enum:
            - GASOLINE
            - DIESEL
            - LIQUEFIED_NATURAL_GAS
            - HYBRID
            - ELECTRIC
        carClass:
          description: Car class
          enum:
            - COMPACT
            - EXECUTIVE
            - MINIVAN
            - SUV
        plateNumber:
          description: Plate number
          type: string
        status:
          description: Car status
          enum:
            - ACTIVE
            - DELETED
    CreateRentalRequest:
      properties:
        carId:
          description: car id
          type: integer
        userId:
          description: user id
          type: integer
        startDate:
          description: ISO 8601 format datetime representing starting time of dropoff slot
          format: date-time
          type: string
        endDate:
          description: ISO 8601 format datetime representing starting time of dropoff slot
          format: date-time
          type: string
        status:
          description: Car status
          enum:
            - ACTIVE
            - DELETED
    RentalResponse:
      properties:
        id:
          description: rental id
          type: integer
        carId:
          description: car id
          type: integer
        userId:
          description: user id
          type: integer
        startDate:
          description: ISO 8601 format datetime representing starting time of dropoff slot
          format: date-time
          type: string
        endDate:
          description: ISO 8601 format datetime representing starting time of dropoff slot
          format: date-time
          type: string
        status:
          description: Car status
          enum:
            - ACTIVE
            - DELETED
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: user id
        username:
          type: string
          example: vladcarcu
        firstName:
          type: string
          example: Vlad
          description: the first name of the user
        lastName:
          type: string
          example: Carcu
          description: the last name of the user
        driverLicense:
          type: string
          example: BV123456
          description: the serie and number of the user's driver's license
        status:
          $ref: '#/components/schemas/UserStatus'
    UserStatus:
      type: string
      enum:
        - ACTIVE
        - DELETED

    CarDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: car id
        make:
          type: string
          example: VW
          description: the make of the car
        model:
          type: string
          example: Golf 7
          description: the model of the car
        year:
          type: integer
          format: int32
          example: 2016
          description: the year in which the car was built
        mileage:
          type: integer
          format: int32
          example: 12350
          description: the approximate mileage when the car is being picked up
        fuel:
          $ref: '#/components/schemas/FuelType'
        carClass:
          $ref: '#/components/schemas/CarClass'
        status:
          $ref: '#/components/schemas/CarStatus'
    FuelType:
      type: string
      enum:
        - GAS
        - DIESEL
    CarClass:
      type: string
      enum:
        - A-segment
        - B-segment
        - C-segment
        - D-segment
        - E-segment
        - F-segment
    CarStatus:
      type: string
      enum:
        - ACTIVE
        - DELETED
    CreatedDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: the id of the created entity
  securitySchemes:
    oAuth:
      type: oauth2
      description: This API uses OAuth2 with the password flow
      flows:
        password:
          tokenUrl: http://localhost:8080/api/oauth/token
          scopes:
            read: get information from the API
            write: use the API to make changes to the supporting data model